// Optional browser verification using an installed Playwright package.
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { once } from 'node:events';
import assert from 'node:assert/strict';
const { chromium }=await import(process.env.PLAYWRIGHT_PATH ? pathToFileURL(process.env.PLAYWRIGHT_PATH).href : 'playwright');
const temp=mkdtempSync(path.join(tmpdir(),'aloven-ui-'));
const child=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'0',DATA_DIR:temp},stdio:['ignore','pipe','pipe']});
let browser;
try {
  const base=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(new Error('Server timeout')),10000);child.stdout.on('data',chunk=>{output+=chunk;const m=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});child.on('exit',()=>{clearTimeout(timer);reject(new Error('Server exit'));});});
  browser=await chromium.launch({headless:true,channel:'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.getByRole('heading',{name:'Configura il tuo reparto'}).waitFor();
  await page.getByLabel('Nome e cognome').fill('Amministratore test');await page.getByLabel('Nome utente',{exact:true}).fill('test');await page.getByLabel('Password',{exact:true}).fill('PasswordTest123!');await page.getByRole('button',{name:'Crea amministratore'}).click();
  await page.getByRole('heading',{name:'Piano di produzione'}).waitFor();
  const queue=page.locator('.backlog [data-task]');const firstId=await queue.nth(0).getAttribute('data-task'),secondId=await queue.nth(1).getAttribute('data-task');
  await page.locator('[data-focus-machine="CNC-01"]').click();assert.equal(await page.locator('.temporal-machine').count(),1);
  await page.locator('[data-focus-day]').first().click();assert.equal(await page.locator('.day-heading').count(),1);assert.equal(await page.locator('[data-drop-machine]').count(),1);
  const focusDate=await page.locator('#date-start').inputValue();await page.getByRole('button',{name:'Giorno successivo',exact:true}).click();assert.notEqual(await page.locator('#date-start').inputValue(),focusDate);await page.getByRole('button',{name:'Giorno precedente',exact:true}).click();assert.equal(await page.locator('#date-start').inputValue(),focusDate);
  const drop=page.locator('[data-drop-machine="CNC-01"]').first();
  await page.locator(`.backlog [data-task="${firstId}"]`).dragTo(drop,{targetPosition:{x:100,y:45}});
  await page.locator(`.backlog [data-task="${firstId}"]`).waitFor({state:'detached'});
  await page.locator(`.backlog [data-detail="${secondId}"]`).click();
  await page.getByLabel('Posizione nella sequenza').selectOption(firstId);await page.getByRole('button',{name:'Pianifica',exact:true}).click();
  await page.getByRole('heading',{name:'Conferma la modifica'}).waitFor();await page.getByRole('button',{name:'Conferma e salva'}).click();await page.locator('#modal').waitFor({state:'hidden'});
  mkdirSync('.artifacts',{recursive:true});await page.screenshot({path:'.artifacts/day-machine-focus.png',fullPage:true});
  const durations=await page.locator('.day-temporal .time-block').evaluateAll(bs=>bs.map(b=>{const times=b.getAttribute('aria-label').match(/(\d\d):(\d\d)–(\d\d):(\d\d)/);return {height:b.getBoundingClientRect().height,minutes:(Number(times[3])*60+Number(times[4]))-(Number(times[1])*60+Number(times[2]))};}));for(const item of durations)assert.ok(Math.abs(item.height-item.minutes*1.3)<1,'Dimensione proporzionale alla durata');
  await page.locator('.time-block').first().hover();await page.locator('#time-tooltip').waitFor({state:'visible'});await page.locator('.time-block').first().focus();assert.ok(await page.locator('#time-tooltip').isVisible());
  await page.getByRole('button',{name:'Ferma macchina',exact:true}).click();await page.getByLabel('Motivo del fermo',{exact:true}).fill('Manutenzione imprevista');await page.locator('#modal').getByRole('button',{name:'Conferma',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('.machine-stopped').waitFor();await page.getByRole('button',{name:'Riattiva macchina',exact:true}).click();await page.locator('#modal').getByRole('button',{name:'Conferma',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'5 giorni',exact:true}).click();await page.getByLabel('Filtra macchina',{exact:true}).selectOption('');assert.equal(await page.locator('.day-heading').count(),5);assert.equal(await page.locator('.temporal-machine').count(),4);
  assert.equal(await page.locator('.backlog [data-task]').count(),62);
  mkdirSync('.artifacts',{recursive:true});await page.screenshot({path:'.artifacts/planning.png',fullPage:true});
  // Task CRUD from real forms, including numeric durations.
  await page.getByRole('button',{name:'Nuova attività',exact:true}).click();await page.getByLabel('Titolo attività').fill('Test UI');await page.getByLabel('Attrezzaggio (minuti)').fill('10');await page.getByLabel('Esecuzione (minuti)').fill('80');
  await page.getByLabel('Componente 1',{exact:true}).selectOption({index:1});await page.getByLabel('Componente 2',{exact:true}).selectOption({index:2});await page.getByLabel('Articolo prodotto',{exact:true}).selectOption({index:1});
  await page.getByLabel('Quantità da produrre').fill('1000');await page.getByLabel('Calcolo del tempo').selectOption('automatic');
  assert.equal(await page.getByLabel('Esecuzione (minuti)').inputValue(),'100');
  await page.getByRole('button',{name:'Salva',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.locator('[data-nav="tasks"]').click();const row=page.getByRole('row').filter({hasText:'Test UI'});await row.getByRole('button',{name:'Modifica'}).click();await page.getByLabel('Titolo attività').fill('Test UI aggiornato');await page.getByRole('button',{name:'Salva',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.getByRole('row').filter({hasText:'Test UI aggiornato'}).getByRole('button',{name:'Elimina'}).click();await page.locator('#modal').getByRole('button',{name:'Elimina',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});
  // Calendar, mass exception and its removal.
  await page.locator('[data-nav="calendar"]').click();await page.getByRole('button',{name:'Imposta periodo'}).click();await page.getByLabel('Dal',{exact:true}).fill('2026-12-24');await page.getByLabel('Al',{exact:true}).fill('2026-12-24');await page.getByLabel('Giorno lavorativo',{exact:true}).uncheck();await page.getByRole('button',{name:'Salva eccezioni'}).click();await page.getByRole('button',{name:'Conferma e salva'}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.getByRole('row').filter({hasText:'24 dicembre 2026'}).waitFor();await page.screenshot({path:'.artifacts/calendar.png',fullPage:true});
  await page.getByRole('button',{name:'Ripristina standard'}).click();await page.getByRole('button',{name:'Conferma e salva'}).click();await page.locator('#modal').waitFor({state:'hidden'});
  // Shared catalogue CRUD and setup rule applied to the existing sequence.
  await page.locator('[data-nav="articles"]').click();await page.getByRole('button',{name:'Nuovo articolo'}).click();await page.getByLabel('Codice articolo',{exact:true}).fill('ART-UI-NEW');await page.getByLabel('Descrizione articolo',{exact:true}).fill('Articolo condiviso test');await page.getByLabel('Utilizzo',{exact:true}).selectOption('product');await page.locator('#modal').getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('button',{name:'Conferma e salva'}).click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.getByRole('row').filter({hasText:'ART-UI-NEW'}).getByRole('button',{name:'Elimina'}).click();await page.locator('#modal').getByRole('button',{name:'Elimina',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});
  await page.locator('[data-nav="setupRules"]').click();await page.getByRole('button',{name:'Nuova regola'}).click();await page.getByLabel('Macchina',{exact:true}).selectOption('CNC-01');await page.getByLabel('Lavorazione precedente').selectOption('fresatura');await page.getByLabel('Lavorazione successiva').selectOption('fresatura');await page.getByLabel('Attrezzaggio del passaggio (minuti)').fill('15');await page.locator('#modal').getByRole('button',{name:'Salva',exact:true}).click();await page.getByRole('button',{name:'Conferma e salva'}).click();await page.locator('#modal').waitFor({state:'hidden'});assert.equal(await page.getByRole('row').filter({hasText:'15 min'}).count(),1);
  await page.locator('[data-nav="shopfloor"]').click();await page.getByLabel('Postazione macchina',{exact:true}).selectOption('CNC-01');
  async function shopAction(action,reason){await page.locator(`[data-shop-action="${action}"]`).click();if(reason)await page.getByLabel('Motivo della sospensione').fill(reason);await page.locator('#modal').getByRole('button',{name:'Conferma',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});}
  await shopAction('start_setup');await page.getByRole('heading',{name:'Completa l’attrezzaggio'}).waitFor();await shopAction('finish_setup');await shopAction('start_run');await shopAction('pause_run','Fine turno');await page.getByRole('heading',{name:'Riprendi quando la macchina è pronta'}).waitFor();await shopAction('resume_run');
  await page.getByRole('link',{name:'Pianificazione',exact:true}).click();await page.locator('[data-machine-stop="CNC-01"]').click();await page.getByLabel('Motivo del fermo').fill('Guasto prova');await page.locator('#modal').getByRole('button',{name:'Conferma',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('[data-nav="shopfloor"]').click();await page.locator('.shop-stop-banner').waitFor();assert.ok(await page.locator('[data-shop-action="resume_run"]').isDisabled());
  await page.getByRole('link',{name:'Pianificazione',exact:true}).click();await page.locator('[data-machine-stop="CNC-01"]').click();await page.locator('#modal').getByRole('button',{name:'Conferma',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('[data-nav="shopfloor"]').click();await page.getByRole('heading',{name:'Riprendi quando la macchina è pronta'}).waitFor();await shopAction('resume_run');
  await page.locator('[data-shop-action="finish_run"]').click();await page.locator('input[name="producedQuantity"]').fill('500');
  await page.locator('[name="scrapQuantity"]').fill('5');await page.locator('[name="scrapReason"]').fill('Difetto bordo');await page.getByLabel('Controllo aspetto',{exact:true}).selectOption('fail');await page.getByLabel('Controllo adesione',{exact:true}).selectOption('pass');await page.getByLabel('Esito qualità',{exact:true}).selectOption('review');await page.locator('[name="qualityNotes"]').fill('Verifica del responsabile sul bordo del rotolo');
  const componentCode=(await page.locator('.lot-group h3').first().textContent()).trim();const scanner=page.locator('[name="component1-barcode-1"]');await scanner.fill('WRONG|ROT-001|350');await scanner.press('Enter');await page.getByText('Il barcode appartiene a un altro componente.',{exact:true}).waitFor();await scanner.fill(`${componentCode}|ROT-001|350`);await scanner.press('Enter');assert.equal(await page.locator('[name="component1-lot-1"]').inputValue(),'ROT-001');assert.equal(await page.locator('[name="component1-quantity-1"]').inputValue(),'350');assert.ok(await page.locator('#modal').isVisible());
  await page.locator('[data-add-lot="component1"]').click();await page.locator('input[name="component1-lot-2"]').fill('ROT-002');await page.locator('input[name="component1-quantity-2"]').fill('155');await page.locator('[name="component2-barcode-1"]').fill('MEM-001');await page.locator('[name="component2-barcode-1"]').press('Enter');await page.locator('input[name="component2-quantity-1"]').fill('510');await page.screenshot({path:'.artifacts/declaration.png',fullPage:true});await page.locator('#modal').getByRole('button',{name:'Dichiara e termina',exact:true}).click();await page.locator('#modal').waitFor({state:'hidden'});await page.getByText('Completata · 500 m lineari',{exact:true}).waitFor();await page.locator('.history-row .quality-badge.review').waitFor();await page.screenshot({path:'.artifacts/shopfloor.png',fullPage:true});
  await page.locator('.history-row').click();await page.getByText('ROT-002',{exact:false}).waitFor();await page.getByText('0.99%',{exact:true}).waitFor();await page.getByText('Motivo scarto: Difetto bordo',{exact:true}).waitFor();await page.screenshot({path:'.artifacts/quality-history.png',fullPage:true});await page.getByRole('button',{name:'Chiudi',exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.artifacts/shopfloor-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Overflow bordo macchina mobile');
  await page.getByRole('link',{name:'Pianificazione',exact:true}).click();assert.equal(await page.locator('.time-block.completed').count(),0);await page.getByLabel('Mostra completate',{exact:true}).check();assert.ok(await page.locator('.time-block.completed').count()>0);await page.screenshot({path:'.artifacts/mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Overflow pagina mobile');
  assert.deepEqual(errors,[],'Errori JavaScript nel browser');console.log('UI verificata: setup, drag-and-drop, inserimento confermato, CRUD attività, calendario ed eccezioni, vista mobile.');
} finally {
  await browser?.close();if(child.exitCode===null){const done=once(child,'exit');child.kill();await done;}rmSync(temp,{recursive:true,force:true});
}
